### ISSUE TITLE
src doesn't update when bound link changes

### ISSUE THREAD

**Issue by lizziekarr** [officert/vue-friendly-iframe#1]
Hi,

Thanks for this component, it works great with a static source link.  It just doesn't seem to update when the data or props are updated.  Am I missing something here?  I know that the link I'm passing to props is updating because I'm rendering it to the page above the iframe.  

Update: Vue devtools shows the correct src link associated with `<FriendlyIframe>`, it just doesn't render correctly.  Are you using lifecycles to handle the update?

```<vue-friendly-iframe :src='link' className='frame'></vue-friendly-iframe>```

Any help is great.  Thanks!

**Comment by officert** [comment]
hey @lizziekarr thanks for catching that! I've just published V0.9.0 which adds supports for this. Also, there's now a documentation site you can find here: https://officert.github.io/vue-friendly-iframe which actually has an example of the changing the iframe src on it.

**Comment by lizziekarr** [comment]
Super cool, thx!

**Comment by Slluxx** [comment]
if you browse inside the iframe, :src should update aswell.
