### ISSUE TITLE
How can i post message to iframe?

### ISSUE THREAD

**Issue by depomguss** [officert/vue-friendly-iframe#13]
My parent Vue:

> <vue-friendly-iframe
>             :style="{ 'display' : iframeLoading ? 'none' : 'block' }"
>             :src="example1Form.src "
>             @load="onLoad"
>             @iframe-load="onIframeLoad"
>             @document-load="onDocumentLoad"
>             frameborder="0"
>             gesture="media"
>             allow="encrypted-media"
>             allowfullscreen="allowfullscreen"
>             width="100%"
>             ref="friendlyIframe"
>           ></vue-friendly-iframe>

My parent send post message function:

> sendPostMessage() {
>       this.$refs.friendlyIframe.iframeEl.contentWindow.postMessage("message");
>     }

------------------------------
My Iframe (Html):

>  <script>
>     	window.addEventListener("message",
>   function (event) {
>     alert() <---------- not working
>   }, false);
>     </script>
>

**Comment by officert** [comment]
I think you need to provide the `targetOrigin` argument when calling `window.postMessage()`

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#Syntax

`this.$refs.friendlyIframe.iframeEl.contentWindow.postMessage("message", "*");` //note the *
