### ISSUE TITLE
Refused to display in a frame because it set 'X-Frame-Options' to 'sameorigin'

### ISSUE THREAD

**Issue by bitcoinvsalts** [officert/vue-friendly-iframe#16]
Hi,

I am getting this error while trying to load an url in the iframe

Here is my code:

```<vue-friendly-iframe src="https://www.google.com"></vue-friendly-iframe>```

Error logs:

```Refused to display 'https://www.google.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.```

```A bad HTTP response code (404) was received when fetching the script.```

**Comment by officert** [comment]
That's because Google's site is preventing it from being loaded in an iframe, try a different site.
