### ISSUE TITLE
Set width and height of iframe

### ISSUE THREAD

**Issue by brampijper** [officert/vue-friendly-iframe#2]
Hi,

First of all nice work on the friendly Iframe!

I'm generating multiple iframes with a different width and height (loaded from a database). I was wondering if it is possible to set the width and height for every iframe?

I've been trying to pass the width and height as props on the vue-friendly-iframe component but it's not working so far. Do you have any tips on implementing this? :)

Thanks!

**Comment by officert** [comment]
Thanks @brampijper! For setting the height and width I would just use some CSS class on each iframe and set the height that way. In the demo you can see I've just set a height of 600px and width of 100% on that iframe.

**Comment by brampijper** [comment]
Great! I fixed it, thanks! 😉

**Comment by thedamon** [comment]
Is there a way to have the iframe always be the full height of its content?

**Comment by officert** [comment]
@thedamon something like this?
```css
iframe {
  height : 100%
}
```

**Comment by thedamon** [comment]
Not really.. thinking about the iframe contents so that the scrollbar is
that of the page rather than the iframe (to make it truly invisible,
especially in cases where the iframe contents change height)

**Comment by officert** [comment]
To do that I think you'd need to resize the iframe anytime the inner page changes size. You can achieve this by using `window.postMessage()` from the page in your iframe, sending the dimensions of the page anytime somethiing changes. Listen for this message in your code containing the iframe and resize the iframe when it happens.

**Comment by nscozzaro** [comment]
I also tried setting `width="100%"` which doesn't work, which led me to stumbling across this issue. So +1 to making this work for this component in the future

**Comment by thedamon** [comment]
It would be quite cool to have this as a  `matchSrcHeight` prop. But I gather i would need to be sending messages from the contained page so it would be difficult to achieve a generic solution

**Comment by officert** [comment]
As I mentioned about the only way to get the iframe to resize based on it's contents is by using `postMessage` and having some code within the iframe sending it's height to an event listener outside the iframe. None of this is in the realm of what this library should be doing. You can access the raw iframe element add doing:

`<vue-friendly-iframe ref="friendlyIframe"></vue-friendly-iframe>`

and then in your Vue component somewhere:

`js
this.$refs.iframeEl.iframe.postMessage()
`
