### ISSUE TITLE
How to avoid the Same-Origin Policy

### ISSUE THREAD

**Issue by torish14** [officert/vue-friendly-iframe#36]
When reading the external source of the iframe tag, the DOM cannot be accessed due to the Same-Origin Policy.
Can this be achieved using the cross-origin attribute?

**Comment by acebelowzero** [comment]
You cannot bypass this. the website must be hosted on the same domain. For the [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) browsers block scripts trying to access a frame with a different origin.

@torish14
