### ISSUE TITLE
css problem

### ISSUE THREAD

**Issue by ych-szh** [officert/vue-friendly-iframe#4]
HI,
Thank you for this great component. I am just not sure how to set style or class to the iframe, like "width:800px;height:1000px".
Thank you for your help!

**Comment by officert** [comment]
@ych-szh you can do it with just plain css. The iframe has a wrapping div with the class `vue-friendly-iframe` on it:

```
.vue-friendly-iframe iframe {
  width : 800px;
  height: 1000px;
}
```

**Comment by ruslankonev** [comment]
@officert how I or you can easily set width & height of frame, if you use a scoped styles? Set it up only with global styles??

**Comment by officert** [comment]
`.vue-friendly-iframe` is a class on the div that wraps the iframe. You can style it however you want like this. Even with scoped styles this should work.

**Comment by ruslankonev** [comment]
With scoped styles, styling a `.vue-friendly-iframe` is not work. I can style this class only with global styles, what is not good

**Comment by ruslankonev** [comment]
With scoped styles, styling a `.vue-friendly-iframe` is not work. I can style this class only with global styles, what is not good

**Comment by NathanDFriend** [comment]
This DOES NOT work with scoped styles. Setting the CSS without scope is the only way to make this work.

**Comment by JoeEarly** [comment]
Ill 2nd that, it does not work with style scoped as I have spent the last hour trying to get it to work until I found this. 

Any plans to fix ?

**Comment by terasum** [comment]
@NathanDFriend Na @JoeEarly 
try this:
```
 &::v-deep .vue-friendly-iframe > iframe {
        width : 100%;
        height: 100%;
     }
```
